# Generated by Django 3.2.3 on 2021-05-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('album_picture', models.CharField(max_length=200)),
                ('spotify_link', models.CharField(max_length=200)),
                ('apple_music_link', models.CharField(max_length=200)),
                ('deezer_link', models.CharField(max_length=200)),
                ('napster_link', models.CharField(max_length=200)),
                ('lyrics', models.TextField()),
            ],
        ),
    ]
