# Generated by Django 3.2.3 on 2021-05-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musics',
            name='apple_music_link',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='musics',
            name='deezer_link',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='musics',
            name='napster_link',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='musics',
            name='spotify_link',
            field=models.CharField(max_length=250),
        ),
    ]
