# Generated by Django 3.2.3 on 2021-05-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musics',
            name='apple_music_link',
        ),
    ]
