# Generated by Django 3.2.3 on 2021-05-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0002_remove_musics_apple_music_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='musics',
            name='apple_music_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
