# Generated by Django 3.1.7 on 2021-05-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0003_musics_apple_music_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musics',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
