# Generated by Django 3.2.3 on 2021-05-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0004_auto_20210520_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='musics',
            name='deezer',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musics',
            name='lyrics',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
